sudo: false

language: ruby

rvm:
  - 2.4.0

cache: bundler
before_install:
  - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null

script: ./deploy.sh
env:  
  global:
    - secure: grp8omoB7hZIgB54QJWiW4+Ur4IAWgmFhoN/5872DhE54aungXvXv92SileXvgM2vvE6AgqEa0nR1NLz0ZSmRBtb/EVk83LCmrb8lIn9OusrB2zyG3hN0nJvccdQqUY+pyHEiF/WuRvSxj+ZhiI2TLolXyB7wlYw9UoWxJL6rRfgcvUcGODR0cLiEKsPx53l7g2ChA+9OYEzDZl5Hob9otILtcJi8QpQkDkzE6FMDpy8QoBy4qh0b3Ae+wxdQBMMjWaPAYQCer0p4YrEhtijIREQDR7ukZMN7jIU0SDWKIWN3lvvI/IWNZyMHtWeeLcNNweUFs9CI0kq2pJObOoqmhmQuXkuBhIP5jGDiW/WuvlR7IPEIcU7Wjz1tuyYZkp+G2mMoCc8Fmt2plsoev21SdNROKeB0kYvZqmEcG5XLv5EyZSFKhPLh0PlhUT9rGft09MXE/oQAZELPLIayS4Z1EnCex5IrMCZDxx/WjRf75u4jzEniu+/y6DVRa33JQ1XUVsodX3AWSZwC1qze5kDEr+mfGhpqs4H/pjqBnPQrN2lmQrLmTkgKD28YQ9qsgzBwhcbVEj6KtJZKOT+tm4cgtinwJ45k0eLNuazsuM7ys66lZqGPqc5ChqbZdxnMqGSr4vfaZIYqFbw2ptFzqK7ZmlB+ASWWpj+lBb32VLvaDo=
