sudo: false

language: ruby

rvm:
  - 2.4.0

cache: bundler
script: bundle exec middleman build

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
  GIT_DEPLOY_EMAIL: "deploy@travis-ci.org"
  github_token: $GITHUB_TOKEN
