sudo: false

language: ruby

rvm:
  - 2.4.0

deploy:
  provider: pages
  skip_cleanup: true
  cache: bundler
  script: bundle exec middleman build
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
