sudo: false

language: ruby

rvm:
  - 2.4.0

deploy:
  provider: pages
  skip_cleanup: true
  script: bash ./deploy.sh
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
