sudo: false

language: ruby

rvm:
  - 2.4.0

cache: bundler
before_install:
  - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null

script: ./deploy.sh
env:  
  global:
    - secure: $GITHUB_TOKEN
